### ISSUE TITLE
load moltin data's

### ISSUE THREAD

**Issue by hitaspdotnet** [pveller/ecommerce-chatbot#1]
@pveller Hi Master. 
How can I loading data from Moltin to Bot and searching them with azure search?
Please help or share any documents about this.
Thanks.
Best regards.

**Comment by pveller** [comment]
That's one piece that I haven't shared yet. Just didn't get to making it pretty. I will do later today or tomorrow. Stay tuned.

**Comment by pveller** [comment]
Sorry for the delay. I just published the script and the instructions on how you can use it:

https://github.com/pveller/ecommerce-chatbot/tree/master/indexes

The only thing that is missing is the script to set up recommendations service. Coming in the next couple days.
